version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  pma-session-store:
services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
      - target: 4001
        published: ${API_PORT:-4001}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/log
        target: /var/log/nginx
      - type: bind
        source: ./src/frontend
        target: /var/www/html


  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./docker/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./src/backend
        target: /var/www/html
      - type: bind
        source: ./docker/php/log
        target: /var/log
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-mydatabase}
      - DB_USERNAME=${DB_USER:-myuser}
      - DB_PASSWORD=${DB_PASS:-mypassword}

  db:
    # image: mysql/mysql-server:8.0
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./docker/mysql/initial.sql
        target: /docker-entrypoint-initdb.d/initial.sql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-mydatabase}
      - MYSQL_USER=${DB_USER:-myuser}
      - MYSQL_PASSWORD=${DB_PASS:-mypassword}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mypassword}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions
    environment:
      - PMA_PORT=${DB_PORT:-3306}
      - PMA_HOST=db
      - PMA_USER=${DB_USER:-myuser}
      - PMA_PASSWORD=${DB_PASS:-mypassword}
